# Site settings
author: Vince Andrew Pimentel
title: 
header-img: img/home-bg.png
email: contact@vincep.me
copyright_name: Vince Andrew Pimentel
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  VincePimentel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
